### ISSUE TITLE
sidekiq_queue config is not honored

### ISSUE THREAD

**Issue by halfbyte** [garaio/xapian_db#44]
I've just noticed that even though the docs say that SidekiqWriter uses 'xapian_db' as the default queue, and even though you should be able to ovewrite the used queue by configuring it with sidekiq_queue: in the yml file, these settings are not honored and all index updates are queued in "default". 

The change to correct the behaviour would be relatively trivial, just adding one line to sidekiq_writer.rb should do the trick:

```ruby
      SidekiqWorker.class_eval do
        include Sidekiq::Worker
        sidekiq_options :queue => XapianDb::Config.sidekiq_queue ## THIS LINE ADDED
      end
```

The reason why I'm not instantly sending a pull request is because I have two questions I would like to have answered from someone before I feel confident to do that:

1. This would probably, without additional changes, break people's installations. If you use additional queues in Sidekiq, you have to configure them explicitly, otherwise they are ignored by the worker process. One solution to this would be to change the "standard" queue for Sidekiq in both code and docs to "default". 

2. While the above change works for me so far, I am not sure if using XapianDB::Config in this manner is particularly safe. I would love to get some feedback from you on this. If it is, fine, if it is not, one solution would be to require a more recent version of sidekiq which has "enqueue_in" methods which would allow us to choose the queue during runtime and not on initialisation.

Please let me know what you think and I'll send a pull request asap.

**Comment by gernotkogler** [comment]
Seems not to be a problem anymore...
