### ISSUE TITLE
Readme describes unimplemented/unfinished features?

### ISSUE THREAD

**Issue by johnmichaelbradley** [garaio/xapian_db#45]
Your readme file mentions the ability to declare datatypes by passing ":as => :json", for instance. However, doing so throws this error when bringing up a console:

/usr/local/rvm/gems/ruby-2.1.2/gems/xapian_db-1.3.5.3/lib/xapian_db/utilities.rb:47:in `assert_valid_keys': Unsupported option(s) detected: as (ArgumentError)

Tracing this back to where assert_valid_keys is being called and adding :as to that list permits the key. I have not tested to see if this has an effect, though.

Also, I am not sure if base_query is fully implemented or if your example is broken. The local variable is reporting as nil:

NoMethodError: undefined method `includes' for nil:NilClass

**Comment by gernotkogler** [comment]
Should work now
