### ISSUE TITLE
base_query example needed

### ISSUE THREAD

**Issue by mmustala** [garaio/xapian_db#47]
I have difficulties in getting the base_query to work.

My Question model belongs to a Region and my blueprint is defined like this:
```
class Question < ActiveRecord::Base

  XapianDb::DocumentBlueprint.setup(:Question) do |blueprint|
    blueprint.attribute :title, as: :string
    blueprint.attribute :region_name do
      region.name
    end
    blueprint.base_query { |q| q.includes(:region) }
  end

  belongs_to :region
end
```
So I took the base_query pretty straight from the Readme where it says `blueprint.base_query { |p| p.includes(:addresses) }`

Now, when I try to reindex the xapian database it says:
```
NoMethodError (undefined method `includes' for nil:NilClass):
```

What am I doing wrong?

**Comment by gernotkogler** [comment]
Hi Mika

Try blueprint.base_query { Question.includes{ [:region] } }

Please note that a base query is optional

**Comment by mmustala** [comment]
Hi,

That did not work. It didn't complain anything but resulted in N+1 queries.
Instead, this works
```
    blueprint.base_query do
      Question.includes(:region)
    end
```

**Comment by gernotkogler** [comment]
My fault. Since we are using squeel, the syntax is a little different. Glad it works for you now.
